
import { UserRole, Language, PageNavItemId, PrayerTime, Team, TaskPriority, TaskCategory, AppTheme, NotificationSound, SafetyChecklistItemDef } from './types';

export const APP_NAME = "Control Shift Pro";
export const COMPANY_NAME_FULL = "الشركة المتحدة لمشتقات الغاز | كنترول | موقع دمياط";
export const COMPANY_LOGO_URL = "https://fakeimg.pl/160x70/1E2A3A/00ACC1/?text=CSP&font_size=32&font=poppins&font_weight=bold";
export const DEFAULT_AVATAR_URL = "https://fakeimg.pl/80x80/2B3F56/E0E0E0/?text=U&font=poppins"; 
export const DISCLAIMER_AGREEMENT_KEY = 'controlShiftPro_disclaimerAgreement_v3';
export const QURAN_RADIO_STREAM_URL = "http://stream.radiojar.com/8s5u5tpdtwzuv";
export const AUTH_TOKEN_KEY = 'controlShiftProAuthToken_v2';
export const REMEMBER_ME_KEY = 'controlShiftProRememberMe_v2';
export const PRAYER_TIMES_API_BASE_URL = "https://api.aladhan.com/v1"; 

export const PRIMARY_COLOR_DARK_HEX = '#1E2A3A';
export const ACCENT_COLOR_DARK_HEX = '#00ACC1';
export const PRIMARY_COLOR_LIGHT_HEX = '#FFFFFF';
export const ACCENT_COLOR_LIGHT_HEX = '#00796B';


export const AVATAR_OPTIONS: string[] = [
  "https://fakeimg.pl/80x80/00ACC1/1E2A3A/?text=E1&font=poppins&font_size=28", 
  "https://fakeimg.pl/80x80/1E2A3A/E0E0E0/?text=SL&font=poppins&font_size=28", 
  "https://fakeimg.pl/80x80/00796B/FFFFFF/?text=UH&font=poppins&font_size=28", 
  "https://fakeimg.pl/80x80/263238/F0F4F8/?text=PO&font=poppins&font_size=28", 
  "https://fakeimg.pl/80x80/F39C12/2C3E50/?text=E2&font=poppins&font_size=28", 
  "https://fakeimg.pl/80x80/3498DB/FFFFFF/?text=A1&font=poppins&font_size=28", 
  "https://fakeimg.pl/80x80/2ECC71/FFFFFF/?text=C1&font=poppins&font_size=28", 
  "https://fakeimg.pl/80x80/E74C3C/FFFFFF/?text=C2&font=poppins&font_size=28", 
  "https://fakeimg.pl/80x80/566573/FFFFFF/?text=G1&font=poppins&font_size=28", 
  "https://fakeimg.pl/80x80/1A2530/00ACC1/?text=G2&font=poppins&font_size=28", 
];

export const ENGINEERS_DATA: { uid: string, name: string, email: string, role: UserRole.ENGINEER, avatarUrl?: string }[] = [
  { uid: 'eng_ahmed_sayed', name: 'أحمد سيد (Ahmed Sayed)', email: 'ahmed.sayed@example.com', role: UserRole.ENGINEER, avatarUrl: AVATAR_OPTIONS[0] },
  { uid: 'eng_haitham_doweidar', name: 'هيثم دويدار (Haitham Doweidar)', email: 'haitham.doweidar@example.com', role: UserRole.ENGINEER, avatarUrl: AVATAR_OPTIONS[4] },
];

export const TEAMS_DATA: Team[] = [
  {
    id: 'team_ahmed_iraqi',
    name: 'وردية أحمد عراقي',
    shiftLeadName: 'أحمد عراقي',
    shiftLeadRole: UserRole.SHIFT_LEAD,
    avatarUrl: AVATAR_OPTIONS[1], 
    members: [
        { name: 'محمد حسن', role: UserRole.PRODUCTION_OPERATOR },
        { name: 'علي كامل', role: UserRole.UNIT_HEAD },
    ]
  },
  {
    id: 'team_abdelnasser_fathy',
    name: 'وردية عبد الناصر فتحي',
    shiftLeadName: 'عبد الناصر فتحي',
    shiftLeadRole: UserRole.SHIFT_LEAD,
    avatarUrl: AVATAR_OPTIONS[6],
    members: [
        { name: 'سارة عبد الله', role: UserRole.PRODUCTION_OPERATOR },
    ]
  },
  {
    id: 'team_mohamed_desouky',
    name: 'وردية محمد دسوقي',
    shiftLeadName: 'محمد دسوقي',
    shiftLeadRole: UserRole.SHIFT_LEAD,
    avatarUrl: AVATAR_OPTIONS[7],
    members: []
  },
  {
    id: 'team_ayman_younes',
    name: 'وردية أيمن يونس',
    shiftLeadName: ' أيمن يونس',
    shiftLeadRole: UserRole.SHIFT_LEAD,
    avatarUrl: AVATAR_OPTIONS[8],
    members: []
  },
];

export const REGISTRATION_ROLES: UserRole[] = [
    UserRole.ENGINEER,
    UserRole.SHIFT_LEAD,
    UserRole.UNIT_HEAD,
    UserRole.PRODUCTION_OPERATOR,
];

export const APP_THEMES: {id: AppTheme, nameKey: string, colors: {primary: string, accent: string} }[] = [
    {id: AppTheme.LIGHT, nameKey: 'lightTheme', colors: {primary: PRIMARY_COLOR_LIGHT_HEX, accent: ACCENT_COLOR_LIGHT_HEX}},
    {id: AppTheme.DARK, nameKey: 'darkTheme', colors: {primary: PRIMARY_COLOR_DARK_HEX, accent: ACCENT_COLOR_DARK_HEX}},
];

export const NOTIFICATION_SOUNDS: {id: NotificationSound, nameKey: string, filePath: string}[] = [
    {id: NotificationSound.DEFAULT, nameKey: 'defaultSound', filePath: '/sounds/default_notification.mp3'},
    {id: NotificationSound.CHIME, nameKey: 'chimeSound', filePath: '/sounds/chime_notification.mp3'},
    {id: NotificationSound.ALERT, nameKey: 'alertSound', filePath: '/sounds/alert_notification.mp3'},
    {id: NotificationSound.NONE, nameKey: 'noSound', filePath: ''}, 
];


export const NAV_ITEMS_EN: {id: PageNavItemId, labelKey: string, icon: string, adminOnly?: boolean, isNew?: boolean }[] = [
    { id: 'dashboard', labelKey: 'dashboard', icon: 'dashboard' },
    { id: 'tasks', labelKey: 'tasks', icon: 'tasks' },
    { id: 'chat', labelKey: 'chat', icon: 'chat'},
    { id: 'ships', labelKey: 'ships', icon: 'ships' },
    { id: 'more', labelKey: 'more', icon: 'more'},
    // Items for "More" screen
    { id: 'shifts', labelKey: 'shifts', icon: 'shifts' },
    { id: 'team', labelKey: 'team', icon: 'team' }, 
    { id: 'userDirectory', labelKey: 'userDirectory', icon: 'userDirectory' }, 
    { id: 'personalCalendar', labelKey: 'personalCalendar', icon: 'personalCalendar' }, 
    { id: 'leaveRequests', labelKey: 'leaveRequests', icon: 'leaveRequests' }, 
    { id: 'entertainment', labelKey: 'entertainment', icon: 'entertainment' },
    { id: 'pid', labelKey: 'pid', icon: 'pid'},
    { id: 'savings', labelKey: 'savings', icon: 'savings', isNew: true }, 
    { id: 'butler', labelKey: 'butler', icon: 'butler'},
    { id: 'reports', labelKey: 'reports', icon: 'reports' },
    { id: 'equipmentLog', labelKey: 'equipmentLog', icon: 'equipmentLog' }, 
    { id: 'safetyChecklist', labelKey: 'safetyChecklist', icon: 'safetyChecklist' },
    { id: 'emergencyContacts', labelKey: 'emergencyContacts', icon: 'emergencyContacts' },
    { id: 'unitConverter', labelKey: 'unitConverter', icon: 'unitConverter' },
    { id: 'documentViewer', labelKey: 'documentViewer', icon: 'documentViewer' }, 
    { id: 'internalNews', labelKey: 'internalNews', icon: 'internalNews' },
    { id: 'feedback', labelKey: 'feedback', icon: 'feedback' },
    { id: 'userGuide', labelKey: 'userGuide', icon: 'userGuide' },
    { id: 'profile', labelKey: 'myProfile', icon: 'profile'},
    { id: 'taskTemplates', labelKey: 'taskTemplates', icon: 'taskTemplates' },
    { id: 'pomodoroTimer', labelKey: 'pomodoroTimer', icon: 'pomodoroTimer' },
    { id: 'kanbanBoard', labelKey: 'kanbanBoard', icon: 'kanbanBoard' }, 
    { id: 'noteTaking', labelKey: 'noteTaking', icon: 'noteTaking' }, 
    { id: 'documentScanner', labelKey: 'documentScanner', icon: 'documentScanner' }, 
    { id: 'learningResources', labelKey: 'learningResources', icon: 'learningResources' }, 
    { id: 'personalExpenses', labelKey: 'personalExpenses', icon: 'personalExpenses' },
    { id: 'goalSetting', labelKey: 'goalSetting', icon: 'goalSetting' },
    { id: 'advancedCalculator', labelKey: 'advancedCalculator', icon: 'advancedCalculator' }, 
    { id: 'shoppingList', labelKey: 'shoppingList', icon: 'shoppingList', isNew: true }, // New
    { id: 'dataExportImport', labelKey: 'dataExportImport', icon: 'dataExportImport' }, 
    { id: 'admin', labelKey: 'admin', icon: 'admin', adminOnly: true },
    { id: 'auditLog', labelKey: 'auditLog', icon: 'auditLog', adminOnly: true }, 
    { id: 'settings', labelKey: 'settings', icon: 'settings' },
];

export const NAV_ITEMS_AR: {id: PageNavItemId, labelKey: string, icon: string, adminOnly?: boolean, isNew?: boolean }[] = [
    { id: 'dashboard', labelKey: 'dashboard', icon: 'dashboard' },
    { id: 'tasks', labelKey: 'tasks', icon: 'tasks' },
    { id: 'chat', labelKey: 'chat', icon: 'chat'},
    { id: 'ships', labelKey: 'ships', icon: 'ships' },
    { id: 'more', labelKey: 'more', icon: 'more'},
    { id: 'shifts', labelKey: 'shifts', icon: 'shifts' },
    { id: 'team', labelKey: 'team', icon: 'team' },
    { id: 'userDirectory', labelKey: 'userDirectory', icon: 'userDirectory' },
    { id: 'personalCalendar', labelKey: 'personalCalendar', icon: 'personalCalendar' },
    { id: 'leaveRequests', labelKey: 'leaveRequests', icon: 'leaveRequests' },
    { id: 'entertainment', labelKey: 'entertainment', icon: 'entertainment' },
    { id: 'pid', labelKey: 'pid', icon: 'pid'},
    { id: 'savings', labelKey: 'savings', icon: 'savings', isNew: true },
    { id: 'butler', labelKey: 'butler', icon: 'butler'},
    { id: 'reports', labelKey: 'reports', icon: 'reports' },
    { id: 'equipmentLog', labelKey: 'equipmentLog', icon: 'equipmentLog' },
    { id: 'safetyChecklist', labelKey: 'safetyChecklist', icon: 'safetyChecklist' },
    { id: 'emergencyContacts', labelKey: 'emergencyContacts', icon: 'emergencyContacts' },
    { id: 'unitConverter', labelKey: 'unitConverter', icon: 'unitConverter' },
    { id: 'documentViewer', labelKey: 'documentViewer', icon: 'documentViewer' },
    { id: 'internalNews', labelKey: 'internalNews', icon: 'internalNews' },
    { id: 'feedback', labelKey: 'feedback', icon: 'feedback' },
    { id: 'userGuide', labelKey: 'userGuide', icon: 'userGuide' },
    { id: 'profile', labelKey: 'myProfile', icon: 'profile'},
    { id: 'taskTemplates', labelKey: 'taskTemplates', icon: 'taskTemplates' },
    { id: 'pomodoroTimer', labelKey: 'pomodoroTimer', icon: 'pomodoroTimer' },
    { id: 'kanbanBoard', labelKey: 'kanbanBoard', icon: 'kanbanBoard' },
    { id: 'noteTaking', labelKey: 'noteTaking', icon: 'noteTaking' },
    { id: 'documentScanner', labelKey: 'documentScanner', icon: 'documentScanner' },
    { id: 'learningResources', labelKey: 'learningResources', icon: 'learningResources' },
    { id: 'personalExpenses', labelKey: 'personalExpenses', icon: 'personalExpenses' },
    { id: 'goalSetting', labelKey: 'goalSetting', icon: 'goalSetting' },
    { id: 'advancedCalculator', labelKey: 'advancedCalculator', icon: 'advancedCalculator' },
    { id: 'shoppingList', labelKey: 'shoppingList', icon: 'shoppingList', isNew: true }, // New
    { id: 'dataExportImport', labelKey: 'dataExportImport', icon: 'dataExportImport' },
    { id: 'admin', labelKey: 'admin', icon: 'admin', adminOnly: true },
    { id: 'auditLog', labelKey: 'auditLog', icon: 'auditLog', adminOnly: true },
    { id: 'settings', labelKey: 'settings', icon: 'settings' },
];

export const EGYPTIAN_CITIES_FOR_PRAYER_TIMES: { name: string, nameAr: string, latitude: number, longitude: number }[] = [
    { name: "Damietta", nameAr: "دمياط", latitude: 31.4164, longitude: 31.8133 },
    { name: "Cairo", nameAr: "القاهرة", latitude: 30.0444, longitude: 31.2357 },
    { name: "Alexandria", nameAr: "الإسكندرية", latitude: 31.2001, longitude: 29.9187 },
    { name: "Giza", nameAr: "الجيزة", latitude: 30.0131, longitude: 31.2089 },
    { name: "Port Said", nameAr: "بور سعيد", latitude: 31.2653, longitude: 32.3018 },
    { name: "Suez", nameAr: "السويس", latitude: 29.9737, longitude: 32.5263 },
];

export const DAMIETTA_PRAYER_TIMES: PrayerTime[] = [
  { nameKey: 'fajr', time: "04:30 AM" },
  { nameKey: 'dhuhr', time: "12:50 PM" },
  { nameKey: 'asr', time: "04:25 PM" },
  { nameKey: 'maghrib', time: "07:45 PM" },
  { nameKey: 'isha', time: "09:15 PM" },
];

export const TASK_PRIORITIES_LIST = [
  { id: TaskPriority.LOW, labelKey: 'priorityLow' },
  { id: TaskPriority.MEDIUM, labelKey: 'priorityMedium' },
  { id: TaskPriority.HIGH, labelKey: 'priorityHigh' },
];

export const TASK_CATEGORIES_LIST = [
  { id: TaskCategory.GENERAL, labelKey: 'categoryGeneral' },
  { id: TaskCategory.MAINTENANCE, labelKey: 'categoryMaintenance' },
  { id: TaskCategory.SAFETY, labelKey: 'categorySafety' },
  { id: TaskCategory.OPERATIONS, labelKey: 'categoryOperations' },
  { id: TaskCategory.PERSONAL, labelKey: 'categoryPersonal' },
];

export const GOAL_CATEGORIES_LIST = [
    { id: 'personal', labelKey: 'goalCategoryPersonal'},
    { id: 'professional', labelKey: 'goalCategoryProfessional'},
    { id: 'health', labelKey: 'goalCategoryHealth'},
    { id: 'finance', labelKey: 'goalCategoryFinance'},
    { id: 'learning', labelKey: 'goalCategoryLearning'},
];

export const EXPENSE_CATEGORIES_LIST = [
    { id: 'transport', labelKey: 'expenseCategoryTransport'},
    { id: 'food', labelKey: 'expenseCategoryFood'},
    { id: 'bills', labelKey: 'expenseCategoryBills'},
    { id: 'housing', labelKey: 'expenseCategoryHousing'},
    { id: 'health', labelKey: 'expenseCategoryHealth'},
    { id: 'entertainment', labelKey: 'expenseCategoryEntertainment'},
    { id: 'education', labelKey: 'expenseCategoryEducation'},
    { id: 'other', labelKey: 'expenseCategoryOther'},
];

export const FEEDBACK_TYPES_LIST = [
    {id: 'bug', labelKey: 'bugReport'},
    {id: 'suggestion', labelKey: 'suggestion'},
    {id: 'compliment', labelKey: 'compliment'},
    {id: 'other', labelKey: 'other'},
];

export const SAFETY_CHECKLIST_ITEMS_DEF: SafetyChecklistItemDef[] = [
    { id: 'ppe_helmet', textKey: 'scl_ppe_helmet', category: 'PPE' },
    { id: 'ppe_gloves', textKey: 'scl_ppe_gloves', category: 'PPE' },
    { id: 'ppe_safety_shoes', textKey: 'scl_ppe_safety_shoes', category: 'PPE' },
    { id: 'ppe_safety_glasses', textKey: 'scl_ppe_safety_glasses', category: 'PPE' },
    { id: 'ppe_harness', textKey: 'scl_ppe_harness', category: 'PPE' },
    { id: 'wa_clear_pathways', textKey: 'scl_wa_clear_pathways', category: 'WorkArea' },
    { id: 'wa_proper_lighting', textKey: 'scl_wa_proper_lighting', category: 'WorkArea' },
    { id: 'wa_fire_extinguishers', textKey: 'scl_wa_fire_extinguishers', category: 'WorkArea' },
    { id: 'wa_emergency_exits', textKey: 'scl_wa_emergency_exits', category: 'WorkArea' },
    { id: 'eq_guards_in_place', textKey: 'scl_eq_guards_in_place', category: 'Equipment' },
    { id: 'eq_no_leaks', textKey: 'scl_eq_no_leaks', category: 'Equipment' },
    { id: 'eq_emergency_stops', textKey: 'scl_eq_emergency_stops', category: 'Equipment' },
    { id: 'pp_work_permit_valid', textKey: 'scl_pp_work_permit_valid', category: 'PermitsProcedures' },
    { id: 'pp_isolation_verified', textKey: 'scl_pp_isolation_verified', category: 'PermitsProcedures' },
    { id: 'pp_gas_test_done', textKey: 'scl_pp_gas_test_done', category: 'PermitsProcedures' },
];

export const EMERGENCY_CONTACT_DEPARTMENTS = [
    { id: 'safety', labelKey: 'departmentSafety' },
    { id: 'medical', labelKey: 'departmentMedical' },
    { id: 'security', labelKey: 'departmentSecurity' },
    { id: 'fire', labelKey: 'departmentFire' },
    { id: 'management', labelKey: 'departmentManagement' },
];

export const INTERNAL_NEWS_CATEGORIES = [
    { id: 'announcements', labelKey: 'newsCategoryAnnouncements' },
    { id: 'maintenance', labelKey: 'newsCategoryMaintenance' },
    { id: 'events', labelKey: 'newsCategoryEvents' },
    { id: 'safety', labelKey: 'newsCategorySafety' },
    { id: 'hr', labelKey: 'newsCategoryHR' },
];

export const UNIT_CONVERSION_TYPES = {
  temperature: [
    { id: 'C', nameKey: 'celsius' }, { id: 'F', nameKey: 'fahrenheit' }, { id: 'K', nameKey: 'kelvin'}
  ],
  pressure: [
    { id: 'psi', nameKey: 'psi' }, { id: 'bar', nameKey: 'bar' }, { id: 'atm', nameKey: 'atm'}, {id: 'kPa', nameKey: 'kilopascal'}
  ],
  length: [
    { id: 'm', nameKey: 'meter' }, { id: 'ft', nameKey: 'feet' }, { id: 'in', nameKey: 'inch'} , {id: 'km', nameKey: 'kilometer'}, {id: 'mi', nameKey: 'mile'}
  ],
};


export const EMOJI_LIST = [
  '😀', '😂', '😍', '🤔', '👍', '👎', '🙏', '🎉', '💯', '🔥', '💪', '💡',
  '☕', '🚀', '⏰', '⏳', '✅', '❌', '⚠️', '👀', '🤷', '💸', '🎂', '🤝'
];

export const translations = {
  [Language.EN]: {
    appName: APP_NAME,
    companyFullName: COMPANY_NAME_FULL,
    splashWelcome: "Welcome to Control Shift Pro!",
    splashMoto: "Optimizing your workflow, one shift at a time. Let's get to work! 🚀",
    splashIntroLine1: "In the heart of industry, where precision meets power...",
    splashIntroLine2: "Control Shift Pro: Your partner in operational excellence.",
    loading: "Loading, please wait...",
    authenticating: "Authenticating...",
    dashboardTitle: "Dashboard Overview",
    myShifts: "My Current Shifts",
    dailyTasks: "Daily Tasks & Log",
    shipOperations: "Vessel Operations",
    addTask: "Add New Task",
    taskDescription: "Task Description",
    taskNotes: "Notes (Optional)",
    taskPriority: "Priority",
    taskCategory: "Category",
    taskDueDate: "Due Date & Time",
    taskEstTime: "Estimated Time (min)",
    taskSubTasks: "Sub-tasks / Checklist",
    addSubTask: "Add sub-task",
    taskRecurrence: "Recurrence",
    noRecurrence: "No Recurrence",
    dailyRecurrence: "Daily",
    weeklyRecurrence: "Weekly",
    monthlyRecurrence: "Monthly",
    saveTask: "Save Task",
    notifications: "Notifications",
    language: "Language",
    english: "English",
    arabic: "العربية",
    currentDateTime: "Current Date & Time",
    date: "Date", 
    shiftName: "Shift Name",
    shiftTime: "Shift Time",
    shiftNotes: "Shift Notes",
    team: "Team",
    noShifts: "No shifts scheduled for you today.",
    pendingTasks: "Pending Tasks",
    completedTasks: "Completed Tasks",
    markComplete: "Mark Complete",
    markIncomplete: "Mark Incomplete",
    shipName: "Vessel Name",
    shipStatus: "Status",
    cargoType: "Cargo Type",
    eta: "ETA",
    etd: "ETD",
    quantity: "Quantity",
    rate: "Rate (per hr)",
    pumpStatus: "Pump Status",
    viewDetails: "View Details",
    settingsTitle: "Application Settings",
    darkMode: "Dark Mode",
    theme: "Theme",
    prayerTimes: "Prayer Times Notifications",
    comicRelief: "Enable Comic Relief Notifications",
    fontSize: "Font Size",
    fontSizeSmall: "Small",
    fontSizeMedium: "Medium",
    fontSizeLarge: "Large",
    notificationSound: "Notification Sound",
    doNotDisturb: "Do Not Disturb",
    prayerTimeLocation: "Prayer Times Location",
    selectLocation: "Select Location...",

    engineer: "Engineer",
    shiftlead: "Shift Lead",
    unithead: "Unit Head",
    productionoperator: "Production Operator",
    admin: "Administrator",
    unknownLead: "Unknown Lead",

    priorityLow: "Low",
    priorityMedium: "Medium",
    priorityHigh: "High",
    categoryGeneral: "General",
    categoryMaintenance: "Maintenance",
    categorySafety: "Safety",
    categoryOperations: "Operations",
    categoryPersonal: "Personal",

    morningShift: "Morning Shift",
    eveningShift: "Evening Shift",
    onLeave: "On Leave",
    import: "Import",
    export: "Export",
    selectTeam: "Select Team / Shift Group",
    selectShift: "Select Shift Type",
    selectDate: "Select Date",
    scheduleShift: "Schedule Shift",
    dailyLog: "Daily Log Entry",
    submitLog: "Submit Log Entry",
    logPlaceholder: "What's crack-a-lackin' today, chief? Spill the beans here...",
    shipments: "Shipments",
    lpg: "LPG",
    lng: "LNG",
    propane: "Propane",
    pumpA: "Pump 700-P-01A",
    pumpB: "Pump 700-P-01B",
    pumpC: "Pump 700-P-01C",
    operational: "Operational",
    offline: "Offline",
    maintenance: "Maintenance",
    addLogEntry: "Add New Log Entry",
    teamActivity: "Team Activity",
    recentNotifications: "Recent Notifications",
    systemMessages: "System Messages",
    viewAll: "View All",
    profile: "Profile",
    myProfile: "My Profile",
    logout: "Logout",
    version: "Version",
    myShiftsToday: "My Shift Today",
    activeShips: "Active Vessels",
    overdueTasks: "Overdue Tasks",
    noPendingTasks: "No pending tasks. Good job! 👍",
    allShifts: "All Scheduled Shifts",
    noShiftsAvailable: "No shifts currently scheduled.",
    addNewShip: "Add New Vessel",
    addShip: "Add Vessel",
    currentShipments: "Current Shipments",
    noShipsData: "No vessel data available.",
    selectLanguage: "Select Application Language",
    engineers: "Engineering Team",
    teamsAndSupervisors: "Shifts, Teams & Leads",
    teamMembers: "Team Members",
    teamPerformance: "Team Performance Overview",
    tasksCompleted: "Tasks Completed",
    hoursWorked: "Hours Worked",
    generateReport: "Generate Detailed Report",
    generateReportDesc: "Create and download a comprehensive PDF report for the selected period.",
    downloadPdfReport: "Download PDF Report",
    printReport: "Print Report",
    shifts: "Shifts", 
    ships: "Ships",
    reports: "Reports",

    mandatoryDisclaimerTitle: "📌 Important Notice Before Using the Application",
    mandatoryDisclaimerWelcome: "We welcome you to this application designed specifically to facilitate daily work tasks, organize shifts, and improve communication among colleagues in the work environment.",
    mandatoryDisclaimerNoticeHeading: "We would like to note the following:",
    mandatoryDisclaimerPoint1: "This application was developed as an unofficial personal initiative from colleagues and does not officially represent the entity or company.",
    mandatoryDisclaimerPoint2: "The purpose of the application is for support and assistance only, and it is not a substitute for any official systems or instructions issued by the management.",
    mandatoryDisclaimerPoint3: "Use of the application is at your own personal responsibility, and neither the developing party nor any colleagues bear responsibility for any decisions or results made based on the information contained within it.",
    mandatoryDisclaimerAppreciation: "We appreciate your understanding and cooperation, and we hope this effort contributes to improving the work environment and facilitating tasks.",
    mandatoryDisclaimerAcknowledgement: "✔ By clicking \"Agree & Continue\" below, you acknowledge that you have read, understood the foregoing, and agree to use the application on that basis.",
    agreeAndContinue: "Agree & Continue",
    exit: "Exit",
    cancel: "Cancel",

    entertainmentTitle: "Entertainment Corner",
    quranRadio: "Quran Radio (Cairo)",
    playRadio: "Play",
    pauseRadio: "Pause",

    loginTitle: "Login to Control Shift Pro",
    signupTitle: "Create New Account",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    nameLabel: "Full Name",
    roleLabel: "Your Role",
    teamAffiliationLabel: "Team / Shift Affiliation",
    selectRole: "Select your role...",
    selectTeamAffiliation: "Select your team...",
    selectAvatar: "Select Avatar",
    orUploadAvatar: "Or upload your own",
    loginButton: "Login",
    signupButton: "Sign Up",
    rememberMe: "Remember Me",
    showPassword: "Show password",
    hidePassword: "Hide password",
    noAccount: "Don't have an account?",
    alreadyAccount: "Already have an account?",
    loginSuccess: "Logged in successfully! Redirecting...",
    signupSuccess: "Account created successfully! Redirecting...",
    authError: "Authentication Error",
    appConfigErrorTitle: "App Configuration Error",
    passwordMismatch: "Passwords do not match!",
    invalidEmail: "Invalid email format.",
    weakPassword: "Password should be at least 6 characters.",
    nameRequired: "Name is required.",
    roleRequired: "Role is required.",
    teamRequired: "Team affiliation is required for your role.",
    avatarFetchError: "Could not fetch avatars. Using default.",

    adminDashboard: "Admin Dashboard",
    pidSymbols: "P&ID Symbols",
    savingsPool: "Colleague Savings Pool (Gam-eya)",
    shiftButler: "Shift Butler (Fahlawy)",
    chat: "Chat / Messaging",

    adminWelcome: "Welcome, Admin! Manage your application settings and users.",
    manageUsers: "Manage Users",
    appSettings: "Application Settings",
    featureToggles: "Feature Toggles",
    quranRadioUrlLabel: "Quran Radio Stream URL:",
    saveAppSettings: "Save Settings",
    settingsSaved: "Application settings saved successfully!",
    errorSavingSettings: "Error saving settings.",
    userManagementTitle: "User Management",
    noUsersFound: "No users found.",
    confirmRoleChange: "Confirm Role Change",
    confirmRoleChangeMsg: "Are you sure you want to change this user's role to {0}?",

    pidIntro: "Common Process and Instrumentation Diagram (P&ID) symbols used in the petroleum and gas industry.",
    pidValve: "Valve (Generic)",
    pidPump: "Pump (Centrifugal)",
    pidTank: "Storage Tank (Atmospheric)",
    pidHeatExchanger: "Heat Exchanger",
    pidCompressor: "Compressor",
    pidInstrument: "Instrument (General)",

    savingsIntro: "Manage or participate in colleague savings pools.",
    createPool: "Create New Pool",
    joinPool: "Join Pool",
    poolName: "Pool Name",
    contributionAmount: "Contribution Amount (EGP)",
    numberOfSlots: "Number of Slots",
    startDate: "Start Date",
    viewPools: "View Available Pools",
    noPoolsAvailable: "No savings pools available currently.",
    poolDetails: "Pool Details",
    participants: "Participants",

    butlerIntro: "Your smart assistant for shift organization and information.",
    askButler: "Ask the Shift Butler...",
    exampleButlerQuery: "e.g., Who is on night shift?",
    butlerResponseLoading: "Fahlawy is thinking...",

    chatIntro: "Communicate with your team or colleagues.",
    sendMessage: "Send Message",
    typeMessage: "Type your message...",
    generalChat: "General Chat Room",
    teamChat: "{0} Team Chat",
    uploadImage: "Upload Image",
    uploadFile: "Upload File",
    chatImageUploaded: "Image uploaded.",
    chatFileUploadError: "File upload failed.",
    userStatusOnline: "Online",
    userStatusOffline: "Offline",
    userStatusBusy: "Busy",
    setUserStatus: "Set your status",
    addReaction: "Add Reaction",
    viewReactions: "View Reactions",
    fileTooLarge: "File is too large (max {0}MB).",
    unsupportedFileType: "Unsupported file type.",

    prayerTimesToday: "Today's Prayer Times ({0})", 
    fajr: "Fajr",
    dhuhr: "Dhuhr",
    asr: "Asr",
    maghrib: "Maghrib",
    isha: "Isha",
    aiWisdomTitle: "Daily Wisdom (AI Powered)",
    aiWisdomPlaceholder: "Today's AI wisdom is brewing... It'll brighten your day! ✨",
    aiRiddleTitle: "Petroleum Riddle (AI Powered)",
    aiRiddlePlaceholder: "A new petroleum riddle daily, powered by AI... Get your thinking cap on! 🤔",
    offlineIndicatorShort: "Offline",
    internetRequiredError: "Internet connection required. This application needs an active connection to function. Please check your connection and try again.",
    more: "More",
    back: "Back",
    dashboard: "Dashboard",
    tasks: "My Tasks",
    
    equipmentLog: "Equipment Log",
    safetyChecklist: "Safety Checklist",
    emergencyContacts: "Emergency Contacts",
    unitConverter: "Unit Converter",
    documentViewer: "Document Viewer",
    internalNews: "Internal News",
    feedback: "Send Feedback",
    userGuide: "User Guide",
    pid: "P&ID Symbols",
    savings: "Savings Pool",
    butler: "Shift Butler",
    taskTemplates: "Task Templates",
    pomodoroTimer: "Pomodoro Timer",
    personalCalendar: "Personal Calendar",
    leaveRequests: "Leave Requests",
    userDirectory: "Colleague Directory",
    auditLog: "Audit Log",
    noteTaking: "My Notes",
    learningResources: "Learning Resources",
    personalExpenses: "Personal Expenses",
    goalSetting: "Goal Setting",
    advancedCalculator: "Advanced Calculator",
    kanbanBoard: "Kanban Board",
    documentScanner: "Document Scanner",
    dataExportImport: "Data Export/Import",
    shoppingList: "Shopping List", 

    equipmentLogTitle: "Equipment Issue Log",
    reportNewIssue: "Report New Issue",
    equipmentNameLabel: "Equipment Name/ID",
    issueDescriptionLabel: "Issue Description",
    issueReportedByLabel: "Reported By",
    issueReportedAtLabel: "Reported At",
    issueStatusLabel: "Status",
    statusReported: "Reported",
    statusInProgress: "In Progress",
    statusResolved: "Resolved",
    adminNotesLabel: "Admin Notes",
    updateStatus: "Update Status",
    submitIssue: "Submit Issue",
    noEquipmentIssues: "No equipment issues reported yet.",
    viewIssue: "View Issue",
    editIssue: "Edit Issue",
    deleteIssue: "Delete Issue",
    confirmDeleteIssue: "Are you sure you want to delete this issue log?",

    safetyChecklistTitle: "Pre-Shift Safety Checklist",
    startChecklist: "Start Checklist",
    checklistForShift: "Checklist for Shift: {0}",
    completeChecklist: "Complete & Submit Checklist",
    checklistOverallNotes: "Overall Notes (Optional)",
    safetyChecklistCompleted: "Safety checklist submitted successfully.",
    scl_ppe_helmet: "Helmet worn correctly?",
    scl_ppe_gloves: "Appropriate gloves worn?",
    scl_ppe_safety_shoes: "Safety shoes in good condition?",
    scl_ppe_safety_glasses: "Safety glasses/goggles worn?",
    scl_ppe_harness: "Safety harness inspected and worn (if applicable)?",
    scl_wa_clear_pathways: "Work area and pathways clear of obstructions?",
    scl_wa_proper_lighting: "Adequate lighting in work area?",
    scl_wa_fire_extinguishers: "Fire extinguishers accessible and charged?",
    scl_wa_emergency_exits: "Emergency exits clear and accessible?",
    scl_eq_guards_in_place: "Machine guards in place and functional?",
    scl_eq_no_leaks: "No visible leaks (oil, gas, water)?",
    scl_eq_emergency_stops: "Emergency stops tested and accessible?",
    scl_pp_work_permit_valid: "Work permit valid and understood?",
    scl_pp_isolation_verified: "Equipment isolation (LOTO) verified?",
    scl_pp_gas_test_done: "Gas test conducted and results satisfactory (if applicable)?",
    checklistCategoryPPE: "Personal Protective Equipment",
    checklistCategoryWorkArea: "Work Area Conditions",
    checklistCategoryEquipment: "Equipment Safety",
    checklistCategoryPermitsProcedures: "Permits & Procedures",
    noSafetyChecklists: "No safety checklists submitted yet.",
    viewChecklist: "View Checklist Details",
    
    departmentSafety: "Safety",
    departmentMedical: "Medical",
    departmentSecurity: "Security",
    departmentFire: "Fire Department",
    departmentManagement: "Management On-Call",
    emergencyContactsTitle: "Emergency Contacts",
    addContact: "Add Contact",
    contactNameLabel: "Contact Name",
    contactNumberLabel: "Phone Number",
    contactDepartmentLabel: "Department",
    contactDescriptionLabel: "Description (Optional)",
    saveContact: "Save Contact",
    noEmergencyContacts: "No emergency contacts listed.",
    deleteContact: "Delete Contact",
    editContact: "Edit Contact",
    confirmDeleteContact: "Are you sure you want to delete this contact?",

    unitConverterTitle: "Unit Converter",
    conversionTypeLabel: "Conversion Type",
    fromUnitLabel: "From Unit",
    toUnitLabel: "To Unit",
    valueToConvertLabel: "Value to Convert",
    convertedValueLabel: "Converted Value",
    convertButton: "Convert",
    selectConversionType: "Select type...",
    temperature: "Temperature",
    pressure: "Pressure",
    length: "Length",
    celsius: "Celsius (°C)",
    fahrenheit: "Fahrenheit (°F)",
    kelvin: "Kelvin (K)",
    psi: "PSI (lb/in²)",
    bar: "Bar",
    atm: "Atmosphere (atm)",
    kilopascal: "Kilopascal (kPa)",
    meter: "Meter (m)",
    feet: "Feet (ft)",
    inch: "Inch (in)",
    kilometer: "Kilometer (km)",
    mile: "Mile (mi)",

    internalNewsTitle: "Internal News & Announcements",
    addNewsArticle: "Add News Article",
    editNewsArticle: "Edit News Article",
    deleteNewsArticle: "Delete News Article",
    confirmDeleteNews: "Are you sure you want to delete this news article?",
    newsTitleLabel: "Article Title",
    newsContentLabel: "Content",
    newsCategoryLabel: "Category",
    newsAuthorLabel: "Author",
    newsPublishedAtLabel: "Published At",
    publishNews: "Publish Article",
    saveNewsChanges: "Save Changes",
    noNewsArticles: "No news articles available.",
    viewArticle: "View Article",
    newsCategoryAnnouncements: "Announcements",
    newsCategoryMaintenance: "Maintenance Alerts",
    newsCategoryEvents: "Events",
    newsCategorySafety: "Safety Updates",
    newsCategoryHR: "HR & Admin",

    feedbackTitle: "Send Feedback",
    feedbackTypeLabel: "Feedback Type",
    feedbackMessageLabel: "Message",
    feedbackPageContextLabel: "Page/Feature (Optional)",
    submitFeedback: "Submit Feedback",
    feedbackSubmitted: "Thank you for your feedback!",
    bugReport: "Bug Report",
    suggestion: "Suggestion",
    compliment: "Compliment",
    other: "Other",
    noFeedbackFound: "No feedback submissions found.",
    markAsRead: "Mark as Read",
    markAsUnread: "Mark as Unread",
    feedbackStatusLabel: "Status",
    statusNew: "New",
    statusArchived: "Archived",

    userGuideTitle: "User Guide & FAQs",
    ug_welcome_title: "Welcome to Control Shift Pro!",
    ug_welcome_content: "This guide helps you get the most out of the app. If you have questions, this is the place to start.",
    ug_tasks_title: "Managing Tasks",
    ug_tasks_content: "Create, edit, and track your daily tasks. Prioritize them and mark them complete as you go.",
    ug_shifts_title: "Shift Management",
    ug_shifts_content: "View your scheduled shifts and team assignments. Shift leads can schedule new shifts.",
    ug_chat_title: "Chat & Communication",
    ug_chat_content: "Use the chat to communicate with your team or colleagues in real-time.",
    
    personalExpensesTitle: "Personal Expense Tracker",
    addExpense: "Add Expense",
    expenseDescriptionLabel: "Description",
    expenseAmountLabel: "Amount (EGP)",
    expenseCategoryLabel: "Category",
    expenseDateLabel: "Date",
    saveExpense: "Save Expense",
    editExpense: "Edit Expense",
    deleteExpense: "Delete Expense",
    confirmDeleteExpense: "Are you sure you want to delete this expense?",
    totalExpenses: "Total Expenses this month: EGP {0}",
    noExpenses: "No expenses logged yet for this period.",
    expenseCategoryTransport: "Transport",
    expenseCategoryFood: "Food",
    expenseCategoryBills: "Bills",
    expenseCategoryHousing: "Housing",
    expenseCategoryHealth: "Health",
    expenseCategoryEntertainment: "Entertainment",
    expenseCategoryEducation: "Education",
    expenseCategoryOther: "Other",

    goalSettingTitle: "Personal & Professional Goals",
    addGoal: "Add New Goal",
    goalTitleLabel: "Goal Title",
    goalDescriptionLabel: "Description (Optional)",
    goalTargetDateLabel: "Target Date (Optional)",
    goalCategoryLabel: "Category",
    markAsAchieved: "Mark as Achieved",
    markAsInProgress: "Mark as In Progress",
    saveGoal: "Save Goal",
    editGoal: "Edit Goal",
    deleteGoal: "Delete Goal",
    confirmDeleteGoal: "Are you sure you want to delete this goal?",
    noGoals: "No goals set yet. Start planning your achievements!",
    goalStatusLabel: "Status",
    statusAchieved: "Achieved",
    statusInProgressGoal: "In Progress", 
    goalCategoryPersonal: "Personal",
    goalCategoryProfessional: "Professional",
    goalCategoryHealth: "Health & Wellness",
    goalCategoryFinance: "Financial",
    goalCategoryLearning: "Learning & Development",

    minutesShort: "min",
    editTask: "Edit Task",
    deleteTask: "Delete Task",
    edit: "Edit",
    delete: "Delete",
    saveChanges: "Save Changes",
    featureUnavailableFromDashboard: "This action is fully available from the Tasks page.",
    
    phoneNumber: "Phone Number",
    birthDate: "Birth Date",
    userPoints: "Points: {0}",
    editProfile: "Edit Profile",
    details: "Details",
    profileUpdatedSuccess: "Profile updated successfully!",

    lightTheme: "Light",
    darkTheme: "Dark",
    oceanBlueTheme: "Ocean Blue",
    desertGoldTheme: "Desert Gold",
    defaultSound: "Default",
    chimeSound: "Chime",
    alertSound: "Alert",
    noSound: "None",

    pomodoroFocusDuration: "Focus Duration (min)",
    pomodoroBreakDuration: "Break Duration (min)",
    pomodoroLinkTask: "Link to Task (Optional)",
    startTimer: "Start Timer",
    pauseTimer: "Pause Timer",
    resumeTimer: "Resume Timer",
    resetTimer: "Reset Timer",
    timerFocusing: "Focusing",
    timerOnBreak: "On Break",
    pomodoroSessionComplete: "Pomodoro Session Complete!",
    takeABreak: "Time for a break!",
    backToFocus: "Back to focus!",
    selectTask: "Select Task...",
    noTasksAvailable: "No tasks available to link.",
    
    searchUser: "Search by name or role...",
    callUser: "Call {0}",
    emailUser: "Email {0}",
    chatWithUser: "Chat with {0}",
    noUsersFoundInDirectory: "No users found.",
    
    addNote: "Add New Note",
    editNote: "Edit Note",
    deleteNote: "Delete Note",
    noteTitleLabel: "Note Title",
    noteContentLabel: "Content",
    saveNote: "Save Note",
    noNotes: "You haven't created any notes yet.",
    confirmDeleteNote: "Are you sure you want to delete this note?",

    addTemplate: "Add New Template",
    editTemplate: "Edit Template",
    deleteTemplate: "Delete Template",
    templateNameLabel: "Template Name",
    useTemplate: "Use Template",
    noTaskTemplates: "No task templates created yet.",
    confirmDeleteTemplate: "Are you sure you want to delete this template?",

    // Learning Resources
    addResource: "Add Resource",
    editResource: "Edit Resource",
    deleteResource: "Delete Resource",
    confirmDeleteResource: "Are you sure you want to delete this learning resource?",
    resourceTitleLabel: "Title",
    resourceDescriptionLabel: "Description (Optional)",
    resourceTypeLabel: "Type",
    resourceTypeLink: "Link",
    resourceTypeDocument: "Document",
    resourceTypeVideo: "Video",
    resourceUrlLabel: "URL (for links)",
    resourceFileLabel: "File (for document/video)",
    resourceCategoryLabel: "Category (Optional)",
    noLearningResources: "No learning resources available yet.",
    viewResource: "View Resource",
    downloadResource: "Download Resource",
    openLink: "Open Link",
    manageLearningResources: "Manage Learning Resources",

    // Leave Requests
    submitLeaveRequest: "Submit Leave Request",
    leaveReasonLabel: "Reason for Leave",
    leaveStartDateLabel: "Start Date",
    leaveEndDateLabel: "End Date",
    leaveStatusLabel: "Status",
    statusPending: "Pending",
    statusApproved: "Approved",
    statusRejected: "Rejected",
    noLeaveRequests: "No leave requests found.",
    viewLeaveRequest: "View Request",
    manageLeaveRequests: "Manage Leave Requests",
    approveLeave: "Approve",
    rejectLeave: "Reject",
    leaveRequestSubmitted: "Leave request submitted successfully.",

    // Document Scanner
    takePhoto: "Take Photo",
    selectFromGallery: "Select from Gallery",
    scannedDocumentPreview: "Document Preview",
    saveScan: "Save Scan (Placeholder)",
    cameraError: "Could not access camera.",

    // Personal Calendar
    calendarView: "Calendar View",
    eventsForDay: "Events for {0}", // {0} is date
    noEventsForDay: "No events scheduled for this day.",

    // Kanban Board
    kanbanToDo: "To Do",
    kanbanInProgress: "In Progress",
    kanbanDone: "Done",
    moveTo: "Move to {0}", // {0} is column name

    // Advanced Calculator
    calculatorDisplay: "Calculator Display",
    clearEntry: "CE",
    clearAll: "C",
    backspace: "⌫",
    memoryClear: "MC",
    memoryRecall: "MR",
    memoryStore: "MS",
    memoryPlus: "M+",
    memoryMinus: "M-",
    sine: "sin",
    cosine: "cos",
    tangent: "tan",
    logarithm: "log",
    squareRoot: "√",
    exponentiation: "x^y",
    piConstant: "π",

    // Data Export/Import
    exportMyData: "Export My Data (Tasks & Notes)",
    importMyData: "Import Data (Placeholder)",
    dataExportedSuccessfully: "Data exported successfully as JSON.",
    errorExportingData: "Error exporting data.",

    // Audit Log (Admin only)
    viewAuditLog: "View Audit Log",
    noAuditLogs: "No audit logs found.",
    auditLogAction: "Action",
    auditLogUser: "User",
    auditLogTimestamp: "Timestamp",
    auditLogDetails: "Details",
    
    // Document Viewer (placeholder page title)
    documentViewerTitle: "Document Viewer",
    
    // Birthday Reminders
    upcomingBirthdays: "Upcoming Birthdays",
    noUpcomingBirthdays: "No upcoming birthdays in the next 7 days.",
    happyBirthdayTo: "Happy Birthday to {0}!",

    // Shopping List
    shoppingListTitle: "Shopping List",
    addShoppingList: "Add New List",
    newListNamePlaceholder: "New list name...",
    addItemToList: "Add Item",
    itemNamePlaceholder: "Item name...",
    itemQuantityPlaceholder: "Quantity (e.g., 1kg, 2 boxes)",
    noShoppingLists: "No shopping lists yet. Create one!",
    markAsPurchased: "Purchased",
    markAsNeeded: "Needed",
    deleteList: "Delete List",
    confirmDeleteList: "Are you sure you want to delete this shopping list and all its items?",
    labelShipsPlural: "Ships",


  },
  [Language.AR]: {
    appName: APP_NAME,
    companyFullName: COMPANY_NAME_FULL,
    splashWelcome: "أهلاً بك في كنترول شيفت برو!",
    splashMoto: "نحو تحسين سير عملك، وردية بعد وردية. هيا بنا نبدأ العمل! 🚀",
    splashIntroLine1: "في قلب الصناعة، حيث تلتقي الدقة بالقوة...",
    splashIntroLine2: "كنترول شيفت برو: شريكك في التميز التشغيلي.",
    loading: "جاري التحميل، من فضلك انتظر...",
    authenticating: "جاري المصادقة...",
    dashboardTitle: "نظرة عامة على لوحة التحكم",
    myShifts: "وردياتي الحالية",
    dailyTasks: "المهام اليومية والسجل",
    shipOperations: "عمليات السفن",
    addTask: "إضافة مهمة جديدة",
    taskDescription: "وصف المهمة",
    taskNotes: "ملاحظات (اختياري)",
    taskPriority: "الأولوية",
    taskCategory: "الفئة",
    taskDueDate: "تاريخ ووقت الاستحقاق",
    taskEstTime: "الوقت المقدر (دقيقة)",
    taskSubTasks: "مهام فرعية / قائمة تحقق",
    addSubTask: "إضافة مهمة فرعية",
    taskRecurrence: "التكرار",
    noRecurrence: "بدون تكرار",
    dailyRecurrence: "يومي",
    weeklyRecurrence: "أسبوعي",
    monthlyRecurrence: "شهري",
    saveTask: "حفظ المهمة",
    notifications: "الإشعارات",
    language: "اللغة",
    english: "English",
    arabic: "العربية",
    currentDateTime: "التاريخ والوقت الحالي",
    date: "التاريخ",
    shiftName: "اسم الوردية",
    shiftTime: "وقت الوردية",
    shiftNotes: "ملاحظات الوردية",
    team: "الفريق",
    noShifts: "لا توجد ورديات مجدولة لك اليوم.",
    pendingTasks: "المهام المعلقة",
    completedTasks: "المهام المكتملة",
    markComplete: "وضع علامة كمكتمل",
    markIncomplete: "وضع علامة كغير مكتمل",
    shipName: "اسم السفينة",
    shipStatus: "الحالة",
    cargoType: "نوع الشحنة",
    eta: "الوقت المتوقع للوصول",
    etd: "الوقت المتوقع للمغادرة",
    quantity: "الكمية",
    rate: "المعدل (لكل ساعة)",
    pumpStatus: "حالة المضخات",
    viewDetails: "عرض التفاصيل",
    settingsTitle: "إعدادات التطبيق",
    darkMode: "الوضع الداكن",
    theme: "المظهر (الثيم)",
    prayerTimes: "إشعارات أوقات الصلاة",
    comicRelief: "تفعيل إشعارات الفكاهة",
    fontSize: "حجم الخط",
    fontSizeSmall: "صغير",
    fontSizeMedium: "متوسط",
    fontSizeLarge: "كبير",
    notificationSound: "صوت الإشعار",
    doNotDisturb: "عدم الإزعاج",
    prayerTimeLocation: "موقع أوقات الصلاة",
    selectLocation: "اختر الموقع...",

    engineer: "مهندس",
    shiftlead: "رئيس وردية",
    unithead: "رئيس وحدة",
    productionoperator: "مشغل إنتاج",
    admin: "مدير النظام",
    unknownLead: "رئيس وردية غير معروف",

    priorityLow: "منخفضة",
    priorityMedium: "متوسطة",
    priorityHigh: "عالية",
    categoryGeneral: "عامة",
    categoryMaintenance: "صيانة",
    categorySafety: "سلامة",
    categoryOperations: "عمليات",
    categoryPersonal: "شخصية",

    morningShift: "وردية صباحية",
    eveningShift: "وردية مسائية",
    onLeave: "في إجازة",
    import: "استيراد",
    export: "تصدير",
    selectTeam: "اختر الفريق / مجموعة الوردية",
    selectShift: "اختر نوع الوردية",
    selectDate: "اختر التاريخ",
    scheduleShift: "جدولة وردية",
    dailyLog: "تسجيل يومي",
    submitLog: "إرسال السجل",
    logPlaceholder: "إيه الدنيا النهاردة يا ريّس؟ احكيلي اللي حصل...",
    shipments: "الشحنات",
    lpg: "غاز بترول مسال",
    lng: "غاز طبيعي مسال",
    propane: "بروبان",
    pumpA: "مضخة 700-P-01A",
    pumpB: "مضخة 700-P-01B",
    pumpC: "مضخة 700-P-01C",
    operational: "فعالة",
    offline: "متوقفة",
    maintenance: "تحت الصيانة",
    addLogEntry: "إضافة سجل جديد",
    teamActivity: "نشاط الفريق",
    recentNotifications: "الإشعارات الأخيرة",
    systemMessages: "رسائل النظام",
    viewAll: "عرض الكل",
    profile: "الملف الشخصي",
    myProfile: "ملفي الشخصي",
    logout: "تسجيل الخروج",
    version: "الإصدار",
    myShiftsToday: "ورديتي اليوم",
    activeShips: "السفن النشطة",
    overdueTasks: "المهام المتأخرة",
    noPendingTasks: "لا توجد مهام معلقة. عاش يا وحش! 👍",
    allShifts: "جميع الورديات المجدولة",
    noShiftsAvailable: "لا توجد ورديات مجدولة حالياً.",
    addNewShip: "إضافة سفينة جديدة",
    addShip: "إضافة سفينة",
    currentShipments: "الشحنات الحالية",
    noShipsData: "لا توجد بيانات عن السفن.",
    selectLanguage: "اختر لغة التطبيق",
    engineers: "فريق المهندسين",
    teamsAndSupervisors: "الورديات، الفرق والقادة",
    teamMembers: "أعضاء الفريق",
    teamPerformance: "نظرة عامة على أداء الفرق",
    tasksCompleted: "المهام المكتملة",
    hoursWorked: "ساعات العمل",
    generateReport: "إنشاء تقرير مفصل",
    generateReportDesc: "إنشاء وتنزيل تقرير PDF شامل للفترة المحددة.",
    downloadPdfReport: "تنزيل تقرير PDF",
    printReport: "طباعة التقرير",
    shifts: "الورديات",
    ships: "السفن",
    reports: "التقارير",

    mandatoryDisclaimerTitle: "📌 تنويه هام قبل استخدام التطبيق",
    mandatoryDisclaimerWelcome: "نرحب بك في هذا التطبيق المصمم خصيصًا لتسهيل مهام العمل اليومية، وتنظيم الورديات، وتحسين التواصل بين الزملاء في بيئة العمل.",
    mandatoryDisclaimerNoticeHeading: "نود التنويه إلى ما يلي:",
    mandatoryDisclaimerPoint1: "هذا التطبيق تم تطويره كمبادرة شخصية غير رسمية من الزملاء، ولا يمثل الجهة أو الشركة رسميًا.",
    mandatoryDisclaimerPoint2: "الغرض من التطبيق هو الدعم والمساعدة فقط، ولا يُعد بديلاً عن أي أنظمة أو تعليمات رسمية صادرة من الإدارة.",
    mandatoryDisclaimerPoint3: "استخدام التطبيق يتم على مسؤوليتك الشخصية، ولا تتحمل الجهة المطورة أو أي من الزملاء المسؤولية عن أي قرارات أو نتائج يتم اتخاذها بناءً على المعلومات الموجودة داخله.",
    mandatoryDisclaimerAppreciation: "نقدر تفهمكم وتعاونكم، ونتمنى أن يساهم هذا الجهد في تحسين بيئة العمل وتسهيل المهام.",
    mandatoryDisclaimerAcknowledgement: "✔ بالضغط على \"موافق ومتابعة\" أدناه، فإنك تقر بأنك قرأت وفهمت ما سبق وتوافق على استخدام التطبيق بناءً على ذلك.",
    agreeAndContinue: "موافق ومتابعة",
    exit: "خروج",
    cancel: "إلغاء",

    entertainmentTitle: "ركن الترفيه",
    quranRadio: "إذاعة القرآن الكريم (القاهرة)",
    playRadio: "تشغيل",
    pauseRadio: "إيقاف مؤقت",

    loginTitle: "تسجيل الدخول إلى كنترول شيفت برو",
    signupTitle: "إنشاء حساب جديد",
    emailLabel: "البريد الإلكتروني",
    passwordLabel: "كلمة المرور",
    confirmPasswordLabel: "تأكيد كلمة المرور",
    nameLabel: "الاسم الكامل",
    roleLabel: "وظيفتك",
    teamAffiliationLabel: "الفريق / الوردية التابع لها",
    selectRole: "اختر وظيفتك...",
    selectTeamAffiliation: "اختر فريقك...",
    selectAvatar: "اختر صورة رمزية",
    orUploadAvatar: "أو قم برفع صورة خاصة بك",
    loginButton: "تسجيل الدخول",
    signupButton: "إنشاء حساب",
    rememberMe: "تذكرني",
    showPassword: "إظهار كلمة المرور",
    hidePassword: "إخفاء كلمة المرور",
    noAccount: "ليس لديك حساب؟",
    alreadyAccount: "لديك حساب بالفعل؟",
    loginSuccess: "تم تسجيل الدخول بنجاح! جاري التوجيه...",
    signupSuccess: "تم إنشاء الحساب بنجاح! جاري التوجيه...",
    authError: "خطأ في المصادقة",
    appConfigErrorTitle: "خطأ في إعدادات التطبيق",
    passwordMismatch: "كلمتا المرور غير متطابقتين!",
    invalidEmail: "صيغة البريد الإلكتروني غير صالحة.",
    weakPassword: "يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.",
    nameRequired: "الاسم مطلوب.",
    roleRequired: "الوظيفة مطلوبة.",
    teamRequired: "الانتماء للفريق مطلوب لوظيفتك.",
    avatarFetchError: "لم نتمكن من جلب الصور الرمزية. سنستخدم الافتراضية.",

    adminDashboard: "لوحة تحكم المشرف",
    pidSymbols: "رموز P&ID",
    savingsPool: "جمعية الزملاء (الجمعية)",
    shiftButler: "فهلوي الوردية",
    chat: "الدردشة / المراسلة",

    adminWelcome: "مرحباً أيها المشرف! قم بإدارة إعدادات التطبيق والمستخدمين.",
    manageUsers: "إدارة المستخدمين",
    appSettings: "إعدادات التطبيق",
    featureToggles: "تفعيل/تعطيل الميزات",
    quranRadioUrlLabel: "رابط بث إذاعة القرآن الكريم:",
    saveAppSettings: "حفظ الإعدادات",
    settingsSaved: "تم حفظ إعدادات التطبيق بنجاح!",
    errorSavingSettings: "خطأ في حفظ الإعدادات.",
    userManagementTitle: "إدارة المستخدمين",
    noUsersFound: "لم يتم العثور على مستخدمين.",
    confirmRoleChange: "تأكيد تغيير الدور",
    confirmRoleChangeMsg: "هل أنت متأكد أنك تريد تغيير دور هذا المستخدم إلى {0}؟",

    pidIntro: "رموز شائعة لمخططات العمليات والأجهزة (P&ID) المستخدمة في صناعة البترول والغاز.",
    pidValve: "صمام (عام)",
    pidPump: "مضخة (طرد مركزي)",
    pidTank: "خزان تخزين (جوي)",
    pidHeatExchanger: "مبادل حراري",
    pidCompressor: "ضاغط",
    pidInstrument: "جهاز قياس (عام)",

    savingsIntro: "إدارة أو المشاركة في جمعيات الزملاء.",
    createPool: "إنشاء جمعية جديدة",
    joinPool: "الانضمام إلى جمعية",
    poolName: "اسم الجمعية",
    contributionAmount: "مبلغ المساهمة (جم)",
    numberOfSlots: "عدد الأدوار",
    startDate: "تاريخ البدء",
    viewPools: "عرض الجمعيات المتاحة",
    noPoolsAvailable: "لا توجد جمعيات متاحة حالياً.",
    poolDetails: "تفاصيل الجمعية",
    participants: "المشاركون",

    butlerIntro: "مساعدك الذكي لتنظيم الوردية والمعلومات.",
    askButler: "اسأل فهلوي الوردية...",
    exampleButlerQuery: "مثال: مين في وردية الليل؟",
    butlerResponseLoading: "الفهلوي بيفكر...",

    chatIntro: "تواصل مع فريقك أو زملائك.",
    sendMessage: "إرسال رسالة",
    typeMessage: "اكتب رسالتك...",
    generalChat: "غرفة الدردشة العامة",
    teamChat: "دردشة فريق {0}",
    uploadImage: "رفع صورة",
    uploadFile: "رفع ملف",
    chatImageUploaded: "تم رفع الصورة.",
    chatFileUploadError: "فشل رفع الملف.",
    userStatusOnline: "متصل",
    userStatusOffline: "غير متصل",
    userStatusBusy: "مشغول",
    setUserStatus: "حدد حالتك",
    addReaction: "إضافة تفاعل",
    viewReactions: "عرض التفاعلات",
    fileTooLarge: "حجم الملف كبير جدا (الحد الأقصى {0} ميجابايت).",
    unsupportedFileType: "نوع الملف غير مدعوم.",

    prayerTimesToday: "مواقيت الصلاة اليوم ({0})",
    fajr: "الفجر",
    dhuhr: "الظهر",
    asr: "العصر",
    maghrib: "المغرب",
    isha: "العشاء",
    aiWisdomTitle: "حكمة اليوم (بالذكاء الاصطناعي)",
    aiWisdomPlaceholder: "حكمة اليوم من الذكاء الاصطناعي بتتحضر... هتنور يومك! ✨",
    aiRiddleTitle: "فزورة بترولية (بالذكاء الاصطناعي)",
    aiRiddlePlaceholder: "فزورة بترولية جديدة كل يوم، بالذكاء الاصطناعي... شغل دماغك! 🤔",
    offlineIndicatorShort: "غير متصل",
    internetRequiredError: "يلزم الاتصال بالإنترنت. يحتاج هذا التطبيق إلى اتصال نشط ليعمل. يرجى التحقق من اتصالك وحاول مرة أخرى.",
    more: "المزيد",
    back: "رجوع",
    dashboard: "لوحة التحكم",
    tasks: "مهامي",
    
    equipmentLog: "سجل المعدات",
    safetyChecklist: "قائمة فحص السلامة",
    emergencyContacts: "جهات اتصال الطوارئ",
    unitConverter: "محول الوحدات",
    documentViewer: "عارض المستندات",
    internalNews: "الأخبار الداخلية",
    feedback: "إرسال ملاحظات",
    userGuide: "دليل المستخدم",
    pid: "رموز P&ID",
    savings: "جمعية الزملاء",
    butler: "فهلوي الوردية",
    taskTemplates: "قوالب المهام",
    pomodoroTimer: "مؤقت بومودورو",
    personalCalendar: "التقويم الشخصي",
    leaveRequests: "طلبات الإجازة",
    userDirectory: "دليل الزملاء",
    auditLog: "سجل التدقيق",
    noteTaking: "ملاحظاتي",
    learningResources: "مصادر تعليمية",
    personalExpenses: "المصروفات الشخصية",
    goalSetting: "تحديد الأهداف",
    advancedCalculator: "آلة حاسبة متقدمة",
    kanbanBoard: "لوحة كانبان",
    documentScanner: "ماسح المستندات ضوئيًا",
    dataExportImport: "تصدير/استيراد البيانات",
    shoppingList: "قائمة التسوق", 
    
    equipmentLogTitle: "سجل أعطال المعدات",
    reportNewIssue: "الإبلاغ عن عطل جديد",
    equipmentNameLabel: "اسم/معرف المعدة",
    issueDescriptionLabel: "وصف العطل",
    issueReportedByLabel: "المبلغ",
    issueReportedAtLabel: "وقت الإبلاغ",
    issueStatusLabel: "الحالة",
    statusReported: "تم الإبلاغ",
    statusInProgress: "قيد المعالجة",
    statusResolved: "تم الحل",
    adminNotesLabel: "ملاحظات الإدارة",
    updateStatus: "تحديث الحالة",
    submitIssue: "إرسال البلاغ",
    noEquipmentIssues: "لا توجد بلاغات أعطال حالياً.",
    viewIssue: "عرض البلاغ",
    editIssue: "تعديل البلاغ",
    deleteIssue: "حذف البلاغ",
    confirmDeleteIssue: "هل أنت متأكد من حذف هذا البلاغ؟",

    safetyChecklistTitle: "قائمة فحص السلامة قبل الوردية",
    startChecklist: "بدء قائمة الفحص",
    checklistForShift: "قائمة فحص لوردية: {0}",
    completeChecklist: "إكمال وإرسال القائمة",
    checklistOverallNotes: "ملاحظات عامة (اختياري)",
    safetyChecklistCompleted: "تم إرسال قائمة فحص السلامة بنجاح.",
    scl_ppe_helmet: "هل الخوذة مجهزة بشكل صحيح؟",
    scl_ppe_gloves: "هل القفازات المناسبة مستخدمة؟",
    scl_ppe_safety_shoes: "هل حذاء السلامة في حالة جيدة؟",
    scl_ppe_safety_glasses: "هل نظارات/واقيات السلامة مستخدمة؟",
    scl_ppe_harness: "هل حزام الأمان مفحوص ومستخدم (إذا لزم الأمر)؟",
    scl_wa_clear_pathways: "هل منطقة العمل والممرات خالية من العوائق؟",
    scl_wa_proper_lighting: "هل الإضاءة كافية في منطقة العمل؟",
    scl_wa_fire_extinguishers: "هل طفايات الحريق متاحة ومشحونة؟",
    scl_wa_emergency_exits: "هل مخارج الطوارئ واضحة ومتاحة؟",
    scl_eq_guards_in_place: "هل واقيات الآلات في مكانها وتعمل؟",
    scl_eq_no_leaks: "هل لا توجد تسريبات مرئية (زيت، غاز، ماء)؟",
    scl_eq_emergency_stops: "هل مفاتيح الإيقاف الطارئ مختبرة ومتاحة؟",
    scl_pp_work_permit_valid: "هل تصريح العمل ساري ومفهوم؟",
    scl_pp_isolation_verified: "هل تم التحقق من عزل المعدات (LOTO)؟",
    scl_pp_gas_test_done: "هل تم إجراء اختبار الغاز والنتائج مرضية (إذا لزم الأمر)؟",
    checklistCategoryPPE: "معدات الوقاية الشخصية",
    checklistCategoryWorkArea: "ظروف منطقة العمل",
    checklistCategoryEquipment: "سلامة المعدات",
    checklistCategoryPermitsProcedures: "التصاريح والإجراءات",
    noSafetyChecklists: "لم يتم إرسال أي قوائم فحص سلامة بعد.",
    viewChecklist: "عرض تفاصيل القائمة",
    
    departmentSafety: "السلامة",
    departmentMedical: "الطبية",
    departmentSecurity: "الأمن",
    departmentFire: "الإطفاء",
    departmentManagement: "الإدارة المناوبة",
    emergencyContactsTitle: "أرقام الطوارئ",
    addContact: "إضافة جهة اتصال",
    contactNameLabel: "اسم جهة الاتصال",
    contactNumberLabel: "رقم الهاتف",
    contactDepartmentLabel: "القسم",
    contactDescriptionLabel: "الوصف (اختياري)",
    saveContact: "حفظ جهة الاتصال",
    noEmergencyContacts: "لا توجد أرقام طوارئ مدرجة.",
    deleteContact: "حذف جهة الاتصال",
    editContact: "تعديل جهة الاتصال",
    confirmDeleteContact: "هل أنت متأكد من حذف جهة الاتصال هذه؟",

    unitConverterTitle: "محول الوحدات",
    conversionTypeLabel: "نوع التحويل",
    fromUnitLabel: "من وحدة",
    toUnitLabel: "إلى وحدة",
    valueToConvertLabel: "القيمة المراد تحويلها",
    convertedValueLabel: "القيمة المحولة",
    convertButton: "تحويل",
    selectConversionType: "اختر النوع...",
    temperature: "درجة الحرارة",
    pressure: "الضغط",
    length: "الطول",
    celsius: "سيلزيوس (°C)",
    fahrenheit: "فهرنهايت (°F)",
    kelvin: "كلفن (K)",
    psi: "رطل/بوصة مربعة (psi)",
    bar: "بار",
    atm: "ضغط جوي (atm)",
    kilopascal: "كيلوباسكال (kPa)",
    meter: "متر (م)",
    feet: "قدم",
    inch: "بوصة",
    kilometer: "كيلومتر (كم)",
    mile: "ميل",

    internalNewsTitle: "الأخبار والإعلانات الداخلية",
    addNewsArticle: "إضافة خبر/إعلان",
    editNewsArticle: "تعديل الخبر",
    deleteNewsArticle: "حذف الخبر",
    confirmDeleteNews: "هل أنت متأكد من حذف هذا الخبر؟",
    newsTitleLabel: "عنوان الخبر",
    newsContentLabel: "المحتوى",
    newsCategoryLabel: "الفئة",
    newsAuthorLabel: "الكاتب",
    newsPublishedAtLabel: "تاريخ النشر",
    publishNews: "نشر الخبر",
    saveNewsChanges: "حفظ التعديلات",
    noNewsArticles: "لا توجد أخبار أو إعلانات حالياً.",
    viewArticle: "عرض الخبر",
    newsCategoryAnnouncements: "إعلانات هامة",
    newsCategoryMaintenance: "تنبيهات الصيانة",
    newsCategoryEvents: "فعاليات وأحداث",
    newsCategorySafety: "تحديثات السلامة",
    newsCategoryHR: "شؤون الموظفين والإدارة",

    feedbackTitle: "إرسال ملاحظاتك",
    feedbackTypeLabel: "نوع الملاحظة",
    feedbackMessageLabel: "الرسالة",
    feedbackPageContextLabel: "الصفحة/الميزة (اختياري)",
    submitFeedback: "إرسال الملاحظات",
    feedbackSubmitted: "شكراً لك على ملاحظاتك القيمة!",
    bugReport: "بلاغ عن خطأ",
    suggestion: "اقتراح",
    compliment: "إشادة",
    other: "أخرى",
    noFeedbackFound: "لا توجد ملاحظات مرسلة.",
    markAsRead: "وضع علامة كمقروء",
    markAsUnread: "وضع علامة كغير مقروء",
    feedbackStatusLabel: "الحالة",
    statusNew: "جديد",
    statusArchived: "مؤرشفة",

    userGuideTitle: "دليل المستخدم والأسئلة الشائعة",
    ug_welcome_title: "مرحباً بك في كنترول شيفت برو!",
    ug_welcome_content: "هذا الدليل يساعدك على الاستفادة القصوى من التطبيق. إذا كانت لديك أسئلة، فهذا هو المكان المناسب للبدء.",
    ug_tasks_title: "إدارة المهام",
    ug_tasks_content: "أنشئ وحرر وتتبع مهامك اليومية. حدد أولوياتها وضع علامة عليها كمكتملة عند الانتهاء.",
    ug_shifts_title: "إدارة الورديات",
    ug_shifts_content: "اطلع على وردياتك المجدولة وتعيينات فريقك. يمكن لرؤساء الورديات جدولة ورديات جديدة.",
    ug_chat_title: "الدردشة والتواصل",
    ug_chat_content: "استخدم الدردشة للتواصل مع فريقك أو زملائك في الوقت الفعلي.",

    personalExpensesTitle: "متتبع المصروفات الشخصية",
    addExpense: "إضافة مصروف",
    expenseDescriptionLabel: "الوصف",
    expenseAmountLabel: "المبلغ (جم)",
    expenseCategoryLabel: "الفئة",
    expenseDateLabel: "التاريخ",
    saveExpense: "حفظ المصروف",
    editExpense: "تعديل المصروف",
    deleteExpense: "حذف المصروف",
    confirmDeleteExpense: "هل أنت متأكد من حذف هذا المصروف؟",
    totalExpenses: "إجمالي المصروفات هذا الشهر: {0} جم",
    noExpenses: "لم يتم تسجيل أي مصروفات لهذه الفترة.",
    expenseCategoryTransport: "مواصلات",
    expenseCategoryFood: "طعام",
    expenseCategoryBills: "فواتير",
    expenseCategoryHousing: "سكن",
    expenseCategoryHealth: "صحة",
    expenseCategoryEntertainment: "ترفيه", 
    expenseCategoryEducation: "تعليم",
    expenseCategoryOther: "أخرى",

    goalSettingTitle: "الأهداف الشخصية والمهنية",
    addGoal: "إضافة هدف جديد",
    goalTitleLabel: "عنوان الهدف",
    goalDescriptionLabel: "الوصف (اختياري)",
    goalTargetDateLabel: "التاريخ المستهدف (اختياري)",
    goalCategoryLabel: "الفئة",
    markAsAchieved: "وضع علامة كمحقق",
    markAsInProgress: "وضع علامة كـ قيد التنفيذ",
    saveGoal: "حفظ الهدف",
    editGoal: "تعديل الهدف",
    deleteGoal: "حذف الهدف",
    confirmDeleteGoal: "هل أنت متأكد من حذف هذا الهدف؟",
    noGoals: "لم يتم تعيين أهداف بعد. ابدأ التخطيط لإنجازاتك!",
    goalStatusLabel: "الحالة",
    statusAchieved: "تم تحقيقه",
    statusInProgressGoal: "قيد التنفيذ",
    goalCategoryPersonal: "شخصي",
    goalCategoryProfessional: "مهني",
    goalCategoryHealth: "صحة وعافية",
    goalCategoryFinance: "مالي",
    goalCategoryLearning: "تعلم وتطوير",

    minutesShort: "د",
    editTask: "تعديل المهمة",
    deleteTask: "حذف المهمة",
    edit: "تعديل",
    delete: "حذف",
    saveChanges: "حفظ التعديلات",
    featureUnavailableFromDashboard: "هذا الإجراء متاح بالكامل من صفحة المهام.",
    
    phoneNumber: "رقم الهاتف",
    birthDate: "تاريخ الميلاد",
    userPoints: "النقاط: {0}",
    editProfile: "تعديل الملف الشخصي",
    details: "التفاصيل",
    profileUpdatedSuccess: "تم تحديث الملف الشخصي بنجاح!",

    lightTheme: "فاتح",
    darkTheme: "داكن",
    oceanBlueTheme: "أزرق محيطي",
    desertGoldTheme: "ذهبي صحراوي",
    defaultSound: "افتراضي",
    chimeSound: "رنين",
    alertSound: "تنبيه",
    noSound: "بدون صوت",

    pomodoroFocusDuration: "مدة التركيز (دقائق)",
    pomodoroBreakDuration: "مدة الراحة (دقائق)",
    pomodoroLinkTask: "ربط بمهمة (اختياري)",
    startTimer: "بدء المؤقت",
    pauseTimer: "إيقاف مؤقت",
    resumeTimer: "استئناف",
    resetTimer: "إعادة ضبط",
    timerFocusing: "وقت التركيز",
    timerOnBreak: "وقت الراحة",
    pomodoroSessionComplete: "اكتملت جلسة بومودورو!",
    takeABreak: "حان وقت الاستراحة!",
    backToFocus: "العودة إلى التركيز!",
    selectTask: "اختر مهمة...",
    noTasksAvailable: "لا توجد مهام متاحة للربط.",

    searchUser: "ابحث بالاسم أو الوظيفة...",
    callUser: "اتصال بـ {0}",
    emailUser: "مراسلة {0} عبر البريد",
    chatWithUser: "دردشة مع {0}",
    noUsersFoundInDirectory: "لم يتم العثور على مستخدمين.",

    addNote: "إضافة ملاحظة جديدة",
    editNote: "تعديل الملاحظة",
    deleteNote: "حذف الملاحظة",
    noteTitleLabel: "عنوان الملاحظة",
    noteContentLabel: "المحتوى",
    saveNote: "حفظ الملاحظة",
    noNotes: "لم تقم بإنشاء أي ملاحظات بعد.",
    confirmDeleteNote: "هل أنت متأكد من حذف هذه الملاحظة؟",

    addTemplate: "إضافة قالب جديد",
    editTemplate: "تعديل القالب",
    deleteTemplate: "حذف القالب",
    templateNameLabel: "اسم القالب",
    useTemplate: "استخدام القالب",
    noTaskTemplates: "لم يتم إنشاء قوالب مهام بعد.",
    confirmDeleteTemplate: "هل أنت متأكد من حذف هذا القالب؟",

    addResource: "إضافة مصدر",
    editResource: "تعديل المصدر",
    deleteResource: "حذف المصدر",
    confirmDeleteResource: "هل أنت متأكد من حذف هذا المصدر التعليمي؟",
    resourceTitleLabel: "العنوان",
    resourceDescriptionLabel: "الوصف (اختياري)",
    resourceTypeLabel: "النوع",
    resourceTypeLink: "رابط",
    resourceTypeDocument: "مستند",
    resourceTypeVideo: "فيديو",
    resourceUrlLabel: "URL (للرابط)",
    resourceFileLabel: "الملف (للمستند/الفيديو)",
    resourceCategoryLabel: "الفئة (اختياري)",
    noLearningResources: "لا توجد مصادر تعليمية متاحة بعد.",
    viewResource: "عرض المصدر",
    downloadResource: "تنزيل المصدر",
    openLink: "فتح الرابط",
    manageLearningResources: "إدارة المصادر التعليمية",

    submitLeaveRequest: "إرسال طلب إجازة",
    leaveReasonLabel: "سبب الإجازة",
    leaveStartDateLabel: "تاريخ البدء",
    leaveEndDateLabel: "تاريخ الانتهاء",
    leaveStatusLabel: "حالة الطلب",
    statusPending: "قيد الانتظار",
    statusApproved: "تمت الموافقة",
    statusRejected: "تم الرفض",
    noLeaveRequests: "لا توجد طلبات إجازة.",
    viewLeaveRequest: "عرض الطلب",
    manageLeaveRequests: "إدارة طلبات الإجازة",
    approveLeave: "موافقة",
    rejectLeave: "رفض",
    leaveRequestSubmitted: "تم إرسال طلب الإجازة بنجاح.",

    takePhoto: "التقاط صورة",
    selectFromGallery: "اختيار من المعرض",
    scannedDocumentPreview: "معاينة المستند الممسوح ضوئيًا",
    saveScan: "حفظ المسح (تجريبي)",
    cameraError: "تعذر الوصول إلى الكاميرا.",

    calendarView: "عرض التقويم",
    eventsForDay: "أحداث يوم {0}", 
    noEventsForDay: "لا توجد أحداث مجدولة لهذا اليوم.",

    kanbanToDo: "المهام المطلوبة",
    kanbanInProgress: "قيد التنفيذ",
    kanbanDone: "تم الإنجاز",
    moveTo: "نقل إلى {0}", 

    calculatorDisplay: "شاشة الآلة الحاسبة",
    clearEntry: "CE",
    clearAll: "C",
    backspace: "⌫",
    memoryClear: "MC",
    memoryRecall: "MR",
    memoryStore: "MS",
    memoryPlus: "M+",
    memoryMinus: "M-",
    sine: "sin",
    cosine: "cos",
    tangent: "tan",
    logarithm: "log",
    squareRoot: "√",
    exponentiation: "x^y",
    piConstant: "π",

    exportMyData: "تصدير بياناتي (المهام والملاحظات)",
    importMyData: "استيراد البيانات (تجريبي)",
    dataExportedSuccessfully: "تم تصدير البيانات بنجاح كملف JSON.",
    errorExportingData: "خطأ في تصدير البيانات.",

    viewAuditLog: "عرض سجل التدقيق",
    noAuditLogs: "لا توجد سجلات تدقيق.",
    auditLogAction: "الإجراء",
    auditLogUser: "المستخدم",
    auditLogTimestamp: "الوقت",
    auditLogDetails: "التفاصيل",
    
    documentViewerTitle: "عارض المستندات",

    // Birthday Reminders
    upcomingBirthdays: "أعياد الميلاد القادمة",
    noUpcomingBirthdays: "لا توجد أعياد ميلاد قادمة خلال الـ 7 أيام القادمة.",
    happyBirthdayTo: "عيد ميلاد سعيد لـ {0}!",

    // Shopping List
    shoppingListTitle: "قائمة التسوق",
    addShoppingList: "إضافة قائمة جديدة",
    newListNamePlaceholder: "اسم القائمة الجديدة...",
    addItemToList: "إضافة عنصر",
    itemNamePlaceholder: "اسم العنصر...",
    itemQuantityPlaceholder: "الكمية (مثال: 1كجم، 2 علبة)",
    noShoppingLists: "لا توجد قوائم تسوق بعد. قم بإنشاء واحدة!",
    markAsPurchased: "تم الشراء",
    markAsNeeded: "مطلوب",
    deleteList: "حذف القائمة",
    confirmDeleteList: "هل أنت متأكد من حذف قائمة التسوق هذه وجميع عناصرها؟",
    labelShipsPlural: "السفن",
  }
};
